export type Country = { name: string; dial: string; iso: string };

// Lista de países con nombre (es), código telefónico (dial) e ISO 3166-1 alpha-2 (iso, minúscula).
// El iso se usa para la bandera vía https://flagcdn.com. Ordenada alfabéticamente por nombre.
export const countries: Country[] = [
  { name: "Afganistán", dial: "+93", iso: "af" },
  { name: "Albania", dial: "+355", iso: "al" },
  { name: "Alemania", dial: "+49", iso: "de" },
  { name: "Andorra", dial: "+376", iso: "ad" },
  { name: "Angola", dial: "+244", iso: "ao" },
  { name: "Antigua y Barbuda", dial: "+1", iso: "ag" },
  { name: "Arabia Saudita", dial: "+966", iso: "sa" },
  { name: "Argelia", dial: "+213", iso: "dz" },
  { name: "Argentina", dial: "+54", iso: "ar" },
  { name: "Armenia", dial: "+374", iso: "am" },
  { name: "Australia", dial: "+61", iso: "au" },
  { name: "Austria", dial: "+43", iso: "at" },
  { name: "Azerbaiyán", dial: "+994", iso: "az" },
  { name: "Bahamas", dial: "+1", iso: "bs" },
  { name: "Bangladés", dial: "+880", iso: "bd" },
  { name: "Barbados", dial: "+1", iso: "bb" },
  { name: "Baréin", dial: "+973", iso: "bh" },
  { name: "Bélgica", dial: "+32", iso: "be" },
  { name: "Belice", dial: "+501", iso: "bz" },
  { name: "Benín", dial: "+229", iso: "bj" },
  { name: "Bielorrusia", dial: "+375", iso: "by" },
  { name: "Bolivia", dial: "+591", iso: "bo" },
  { name: "Bosnia y Herzegovina", dial: "+387", iso: "ba" },
  { name: "Botsuana", dial: "+267", iso: "bw" },
  { name: "Brasil", dial: "+55", iso: "br" },
  { name: "Brunéi", dial: "+673", iso: "bn" },
  { name: "Bulgaria", dial: "+359", iso: "bg" },
  { name: "Burkina Faso", dial: "+226", iso: "bf" },
  { name: "Burundi", dial: "+257", iso: "bi" },
  { name: "Bután", dial: "+975", iso: "bt" },
  { name: "Cabo Verde", dial: "+238", iso: "cv" },
  { name: "Camboya", dial: "+855", iso: "kh" },
  { name: "Camerún", dial: "+237", iso: "cm" },
  { name: "Canadá", dial: "+1", iso: "ca" },
  { name: "Catar", dial: "+974", iso: "qa" },
  { name: "Chad", dial: "+235", iso: "td" },
  { name: "Chile", dial: "+56", iso: "cl" },
  { name: "China", dial: "+86", iso: "cn" },
  { name: "Chipre", dial: "+357", iso: "cy" },
  { name: "Ciudad del Vaticano", dial: "+39", iso: "va" },
  { name: "Colombia", dial: "+57", iso: "co" },
  { name: "Comoras", dial: "+269", iso: "km" },
  { name: "Corea del Norte", dial: "+850", iso: "kp" },
  { name: "Corea del Sur", dial: "+82", iso: "kr" },
  { name: "Costa de Marfil", dial: "+225", iso: "ci" },
  { name: "Costa Rica", dial: "+506", iso: "cr" },
  { name: "Croacia", dial: "+385", iso: "hr" },
  { name: "Cuba", dial: "+53", iso: "cu" },
  { name: "Dinamarca", dial: "+45", iso: "dk" },
  { name: "Dominica", dial: "+1", iso: "dm" },
  { name: "Ecuador", dial: "+593", iso: "ec" },
  { name: "Egipto", dial: "+20", iso: "eg" },
  { name: "El Salvador", dial: "+503", iso: "sv" },
  { name: "Emiratos Árabes Unidos", dial: "+971", iso: "ae" },
  { name: "Eritrea", dial: "+291", iso: "er" },
  { name: "Eslovaquia", dial: "+421", iso: "sk" },
  { name: "Eslovenia", dial: "+386", iso: "si" },
  { name: "España", dial: "+34", iso: "es" },
  { name: "Estados Unidos", dial: "+1", iso: "us" },
  { name: "Estonia", dial: "+372", iso: "ee" },
  { name: "Esuatini", dial: "+268", iso: "sz" },
  { name: "Etiopía", dial: "+251", iso: "et" },
  { name: "Filipinas", dial: "+63", iso: "ph" },
  { name: "Finlandia", dial: "+358", iso: "fi" },
  { name: "Fiyi", dial: "+679", iso: "fj" },
  { name: "Francia", dial: "+33", iso: "fr" },
  { name: "Gabón", dial: "+241", iso: "ga" },
  { name: "Gambia", dial: "+220", iso: "gm" },
  { name: "Georgia", dial: "+995", iso: "ge" },
  { name: "Ghana", dial: "+233", iso: "gh" },
  { name: "Granada", dial: "+1", iso: "gd" },
  { name: "Grecia", dial: "+30", iso: "gr" },
  { name: "Guatemala", dial: "+502", iso: "gt" },
  { name: "Guyana", dial: "+592", iso: "gy" },
  { name: "Guinea", dial: "+224", iso: "gn" },
  { name: "Guinea-Bisáu", dial: "+245", iso: "gw" },
  { name: "Guinea Ecuatorial", dial: "+240", iso: "gq" },
  { name: "Haití", dial: "+509", iso: "ht" },
  { name: "Honduras", dial: "+504", iso: "hn" },
  { name: "Hungría", dial: "+36", iso: "hu" },
  { name: "India", dial: "+91", iso: "in" },
  { name: "Indonesia", dial: "+62", iso: "id" },
  { name: "Irak", dial: "+964", iso: "iq" },
  { name: "Irán", dial: "+98", iso: "ir" },
  { name: "Irlanda", dial: "+353", iso: "ie" },
  { name: "Islandia", dial: "+354", iso: "is" },
  { name: "Islas Marshall", dial: "+692", iso: "mh" },
  { name: "Islas Salomón", dial: "+677", iso: "sb" },
  { name: "Israel", dial: "+972", iso: "il" },
  { name: "Italia", dial: "+39", iso: "it" },
  { name: "Jamaica", dial: "+1", iso: "jm" },
  { name: "Japón", dial: "+81", iso: "jp" },
  { name: "Jordania", dial: "+962", iso: "jo" },
  { name: "Kazajistán", dial: "+7", iso: "kz" },
  { name: "Kenia", dial: "+254", iso: "ke" },
  { name: "Kirguistán", dial: "+996", iso: "kg" },
  { name: "Kiribati", dial: "+686", iso: "ki" },
  { name: "Kuwait", dial: "+965", iso: "kw" },
  { name: "Laos", dial: "+856", iso: "la" },
  { name: "Lesoto", dial: "+266", iso: "ls" },
  { name: "Letonia", dial: "+371", iso: "lv" },
  { name: "Líbano", dial: "+961", iso: "lb" },
  { name: "Liberia", dial: "+231", iso: "lr" },
  { name: "Libia", dial: "+218", iso: "ly" },
  { name: "Liechtenstein", dial: "+423", iso: "li" },
  { name: "Lituania", dial: "+370", iso: "lt" },
  { name: "Luxemburgo", dial: "+352", iso: "lu" },
  { name: "Madagascar", dial: "+261", iso: "mg" },
  { name: "Malasia", dial: "+60", iso: "my" },
  { name: "Malaui", dial: "+265", iso: "mw" },
  { name: "Maldivas", dial: "+960", iso: "mv" },
  { name: "Malí", dial: "+223", iso: "ml" },
  { name: "Malta", dial: "+356", iso: "mt" },
  { name: "Marruecos", dial: "+212", iso: "ma" },
  { name: "Mauricio", dial: "+230", iso: "mu" },
  { name: "Mauritania", dial: "+222", iso: "mr" },
  { name: "México", dial: "+52", iso: "mx" },
  { name: "Micronesia", dial: "+691", iso: "fm" },
  { name: "Moldavia", dial: "+373", iso: "md" },
  { name: "Mónaco", dial: "+377", iso: "mc" },
  { name: "Mongolia", dial: "+976", iso: "mn" },
  { name: "Montenegro", dial: "+382", iso: "me" },
  { name: "Mozambique", dial: "+258", iso: "mz" },
  { name: "Myanmar", dial: "+95", iso: "mm" },
  { name: "Namibia", dial: "+264", iso: "na" },
  { name: "Nauru", dial: "+674", iso: "nr" },
  { name: "Nepal", dial: "+977", iso: "np" },
  { name: "Nicaragua", dial: "+505", iso: "ni" },
  { name: "Níger", dial: "+227", iso: "ne" },
  { name: "Nigeria", dial: "+234", iso: "ng" },
  { name: "Noruega", dial: "+47", iso: "no" },
  { name: "Nueva Zelanda", dial: "+64", iso: "nz" },
  { name: "Omán", dial: "+968", iso: "om" },
  { name: "Países Bajos", dial: "+31", iso: "nl" },
  { name: "Pakistán", dial: "+92", iso: "pk" },
  { name: "Palaos", dial: "+680", iso: "pw" },
  { name: "Palestina", dial: "+970", iso: "ps" },
  { name: "Panamá", dial: "+507", iso: "pa" },
  { name: "Papúa Nueva Guinea", dial: "+675", iso: "pg" },
  { name: "Paraguay", dial: "+595", iso: "py" },
  { name: "Perú", dial: "+51", iso: "pe" },
  { name: "Polonia", dial: "+48", iso: "pl" },
  { name: "Portugal", dial: "+351", iso: "pt" },
  { name: "Reino Unido", dial: "+44", iso: "gb" },
  { name: "República Centroafricana", dial: "+236", iso: "cf" },
  { name: "República Checa", dial: "+420", iso: "cz" },
  { name: "República del Congo", dial: "+242", iso: "cg" },
  { name: "República Democrática del Congo", dial: "+243", iso: "cd" },
  { name: "República Dominicana", dial: "+1", iso: "do" },
  { name: "Ruanda", dial: "+250", iso: "rw" },
  { name: "Rumania", dial: "+40", iso: "ro" },
  { name: "Rusia", dial: "+7", iso: "ru" },
  { name: "Samoa", dial: "+685", iso: "ws" },
  { name: "San Cristóbal y Nieves", dial: "+1", iso: "kn" },
  { name: "San Marino", dial: "+378", iso: "sm" },
  { name: "San Vicente y las Granadinas", dial: "+1", iso: "vc" },
  { name: "Santa Lucía", dial: "+1", iso: "lc" },
  { name: "Santo Tomé y Príncipe", dial: "+239", iso: "st" },
  { name: "Senegal", dial: "+221", iso: "sn" },
  { name: "Serbia", dial: "+381", iso: "rs" },
  { name: "Seychelles", dial: "+248", iso: "sc" },
  { name: "Sierra Leona", dial: "+232", iso: "sl" },
  { name: "Singapur", dial: "+65", iso: "sg" },
  { name: "Siria", dial: "+963", iso: "sy" },
  { name: "Somalia", dial: "+252", iso: "so" },
  { name: "Sri Lanka", dial: "+94", iso: "lk" },
  { name: "Sudáfrica", dial: "+27", iso: "za" },
  { name: "Sudán", dial: "+249", iso: "sd" },
  { name: "Sudán del Sur", dial: "+211", iso: "ss" },
  { name: "Suecia", dial: "+46", iso: "se" },
  { name: "Suiza", dial: "+41", iso: "ch" },
  { name: "Surinam", dial: "+597", iso: "sr" },
  { name: "Tailandia", dial: "+66", iso: "th" },
  { name: "Tanzania", dial: "+255", iso: "tz" },
  { name: "Tayikistán", dial: "+992", iso: "tj" },
  { name: "Timor Oriental", dial: "+670", iso: "tl" },
  { name: "Togo", dial: "+228", iso: "tg" },
  { name: "Tonga", dial: "+676", iso: "to" },
  { name: "Trinidad y Tobago", dial: "+1", iso: "tt" },
  { name: "Túnez", dial: "+216", iso: "tn" },
  { name: "Turkmenistán", dial: "+993", iso: "tm" },
  { name: "Turquía", dial: "+90", iso: "tr" },
  { name: "Tuvalu", dial: "+688", iso: "tv" },
  { name: "Ucrania", dial: "+380", iso: "ua" },
  { name: "Uganda", dial: "+256", iso: "ug" },
  { name: "Uruguay", dial: "+598", iso: "uy" },
  { name: "Uzbekistán", dial: "+998", iso: "uz" },
  { name: "Vanuatu", dial: "+678", iso: "vu" },
  { name: "Venezuela", dial: "+58", iso: "ve" },
  { name: "Vietnam", dial: "+84", iso: "vn" },
  { name: "Yemen", dial: "+967", iso: "ye" },
  { name: "Yibuti", dial: "+253", iso: "dj" },
  { name: "Zambia", dial: "+260", iso: "zm" },
  { name: "Zimbabue", dial: "+263", iso: "zw" },
];
